class HelpView():
    def show_help(self):
        print('Keys:')
        print(f'"w": move up')
        print(f'"s": move down')
        print(f'"a": move left')
        print(f'"d": move right')
        print(f'"r": pick up item')
        print(f'"t": change icon\n')
        print('Interactables:')
        print(f'"O": Healing altar ("Stone table with a bowl of water")')
        print(f'"U": Magic mirror ("A glass to which the images of whole floor were directed. There is very small inscription saying CCTV")')
        print(f'"C": Chest ("A wooden chest. There’s something glimmering inside it")\n')
        print('Enemies:')
        print(f'"S": Satyr ("A man with legs, tail and ears of a horse")')
        print(f'"A": Dog ("A dog. Yes, gods have dogs, why wouldn’t they?")')
        print(f'"H": Hoplite ("A warrior with spear and shield, selected by Zeus to guard this place")')
        print(f'"E": Erinya ("A woman with bat wings, snakes for hairs and black body")')
        print(f'"b": Heaven Cyclop ("This guy was busy forging lightnings and he’s not happy to see you here")')
        print(f'"T": Titan ("An old god. Very old, actually")')
        print(f'"P": Pegasus ("Basically a horse with wings")')
        print(f'"N": Centaur ("A horse with a torso of the man. His hair and fur are white and he’s armed")')
        print(f'"Z": Zeus ("That’s the guy you want to take revenge on! Get him!")\n')
        print('NPCs:')
        print(f'"W": Athena\'s owl ("Somehow there is a lot of wisdom in it\'s eyes")')
        print(f'"C": Cat ("It’s a cute, furry creature. Awwww.")\n')
        print('Press Esc to go back to main menu')
